#!/bin/sh

mkdir -p ../bin
mkdir -p ../bin/libaskue

all=$( find ../src/ -type f -name "*.h" )

main="libaskue.h"

for src in $all 
do
    dest=$( basename $src )
    
    if [ "$dest" != "$main" ]
    then
        cp $src ../bin/libaskue/$dest
    else
        cp $src ../bin/$dest
    fi
done

mv $1 ../bin/$1
